export enum NotificationJobNames {
  REGISTER_USER = 'REGISTER_USER',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  AUTH_SENDOTP = 'AUTH_SENDOTP',
  APPOINTMENT_CANCEL = 'APPOINTMENT_CANCEL',
  APPOINTMENT_UPDATE = 'APPOINTMENT_UPDATE',
  TRANSACTION_CREATE = 'TRANSACTION_CREATE',
  TRANSACTION_UPDATE = 'TRANSACTION_UPDATE',
}
